export interface currentCourse{
  id:string,
  courseInfoId:string,
  lectureDay:string,
  lectureSession:string,
  lectureVenue:string,
  medium:string,
  practicalDay:string,
  practicalSession:string,
  practicalVenue:string,
  checkEdit:boolean,
  telephoneNo:string,
  references:{
    referenceId:string,
    reference:string,
    referCheck:boolean,
  },
  room:string,
  skill:string,
  teachTable:{
    teachTableId:string,
    checkTeachTable:boolean,
    weekOtherDesc:string,
    teachRef:{
      teachRefId:string,
      timeTableRef:string,
      checkRef:boolean,
      rowId:string,
    },
    weekInfo:{
      activityDesc:string,
      activityId:string,
      activityType:string,
      checkWeekInfo:boolean,
      rowId:string,
    }
  }
}
